title: Say No to PACT
author: Lower Manhattan Against PACT
email: d1@council.nyc.gov
description: > # this means to ignore newlines until "show_exerpts:"
  Protect Your Home! Say NO to PACT at Seward Park Extension and Annex!
  拒绝私有化，拒绝PACT，保护你的公寓！
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: ''

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Why You Should Say No to PACT
  tagline: Don't Sell Out Your Own Home For A Private Company To Profit
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: Home
      url: '/index.html'
    - title: Get Involved
      url: '/posts/involved/'

  # generate social links in footer
  social_links:
    instagram: nycdistrict1


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
 # - index.md
  #- index.html

# Build settings
# theme: texture
remote_theme: samarsault/texture
plugins:
  - jekyll-seo-tag
  - jekyll-feed
